# Generated by Django 3.0.3 on 2020-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
