# Generated by Django 3.0.3 on 2020-06-22 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('author', models.CharField(max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(help_text='not more than 1500 words', max_length=1500)),
                ('video_link', models.URLField()),
                ('photo', models.URLField(default='insert photo link here')),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
